# Generated by Django 3.1.2 on 2023-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_auto_20230506_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year'), ('4 year', '4 year'), ('5 year', '5 year'), ('6 year', '6 year'), ('7 year', '7 year'), ('8 year', '8 year'), ('9 year', '9 year'), ('10 year', '10 year'), ('11 year', '11 year'), ('12 year', '12 year')], max_length=100),
        ),
    ]
